# Generated by Django 5.2.7 on 2025-12-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_deleted_at_community_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='slug',
        ),
    ]
