# Generated by Django 5.2.7 on 2025-12-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='public'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('organizer', 'Organizer')]),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('banned', 'Banned')]),
        ),
    ]
