# Generated by Django 5.2.7 on 2025-11-23 14:17

import apps.users.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, help_text='First name of the user.', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user.', max_length=30, verbose_name='last name')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the user.', max_length=100, verbose_name='full name')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters and digits only.', max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(db_index=True, help_text='Required. Enter a valid email address.', max_length=150, unique=True, validators=[apps.users.validators.validate_email_domain], verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the user.', max_length=15, null=True, verbose_name='phone number')),
                ('city', models.CharField(blank=True, help_text='City of the user.', max_length=30, null=True, verbose_name='city')),
                ('country', models.CharField(blank=True, help_text='Country of the user.', max_length=30, null=True, verbose_name='country')),
                ('birthdate', models.DateField(blank=True, help_text='Birthdate of the user.', null=True, verbose_name='birthdate')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the user joined.', verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, help_text="The date and time of the user's last login.", null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='image', max_length=20)),
                ('file', models.FileField(upload_to='media_files/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
