# Generated by Django 5.2.7 on 2025-12-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-created_at']},
        ),
    ]
