# Generated by Django 5.2.7 on 2025-12-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_actor_and_more'),
        ('notifications', '0003_notification_fields'),
    ]

    operations = [
    ]
